services: mysql
before_script:
  - mysql -e "CREATE DATABASE babylonia_test;"
  - mysql -e "CREATE USER 'developer'@'localhost' IDENTIFIED BY '';"
  - mysql -e "GRANT ALL PRIVILEGES ON babylonia_test.* TO 'developer'@'localhost' WITH GRANT OPTION;"
language: ruby
env:
  - "ACTIVE_RECORD_VERSION='~> 3.2'"
  - "ACTIVE_RECORD_VERSION='>= 4.0.0'"
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - rbx-20mode
  - jruby-19mode
  - jruby-20mode
  
script: bundle exec rspec