services: mysql
before_script:
  - mysql -e "CREATE DATABASE babylonia_test;"
language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx
  - jruby-19mode
  - jruby-20mode

gemfile:
  - gemfiles/4.0.Gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/3.1.Gemfile  

script: "bundle install && bundle exec rake spec"

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/4.0-jruby.Gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/3.2-jruby.Gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/3.1-jruby.Gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/4.0-jruby.Gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/3.2-jruby.Gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/3.1-jruby.Gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/4.0-jruby.Gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/3.2-jruby.Gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/3.1-jruby.Gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/4.0.Gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/3.2.Gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/3.1.Gemfile
    - rvm: jruby-20mode
      gemfile: gemfiles/4.0.Gemfile
    - rvm: jruby-20mode
      gemfile: gemfiles/3.2.Gemfile
    - rvm: jruby-20mode
      gemfile: gemfiles/3.1.Gemfile
  allow_failures:
    - rvm: 2.1.0