services: mysql
before_script:
  - mysql -e 'CREATE DATABASE babylonia_test;'
  - mysql -e 'CREATE USER 'developer'@'localhost' IDENTIFIED BY '';'
  - mysql -e 'GRANT ALL PRIVILEGES ON *.* TO 'developer'@'localhost' WITH GRANT OPTION;'
  
language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - rbx-20mode
  - jruby-19mode
  - jruby-20mode
  
script: bundle exec rspec