global: &global
  reconnect: true
  adapter: mysql2
  encoding: utf8

base: &base
  username: developer
  password:
  host: 127.0.0.1
  application_timezone: :local
  
test:
  <<: *global
  <<: *base
  database: babylonia_test